

import sys
sys.path.append("..")

from fastapi import Depends, APIRouter, Request, Form, HTTPException
import models
from database import engine, SessionLocal
from sqlalchemy.orm import Session
from .auth import get_current_user
from fastapi.responses import JSONResponse
from starlette import status
import schemas

router = APIRouter(
    prefix="/todos",
    tags=["todos"],
    responses={404: {"description": "Not found"}}
)

models.Base.metadata.create_all(bind=engine)


def get_db():
    try:
        db = SessionLocal()
        yield db
    finally:
        db.close()



@router.get("/", response_class=JSONResponse)
async def read_all_by_user(request: Request, db: Session = Depends(get_db)):

    user = await get_current_user(request)
    if user is None:
        return JSONResponse(content={"error": "Unauthorized"}, status_code=status.HTTP_401_UNAUTHORIZED)

    todos = db.query(models.Todos).filter(models.Todos.owner_id == user.get("id")).all()
    todos_json = [{"id": todo.id, "title": todo.title, "description": todo.description, "priority": todo.priority, "complete": todo.complete} for todo in todos]

    return JSONResponse(content=todos_json)

@router.post("/add-todo", response_model=schemas.Todos)
async def create_todo(request: Request, todo_add: dict, db: Session = Depends(get_db)):
    # print("tanvir 1")
    user = await get_current_user(request)
    if user is None:
        raise HTTPException(status_code=401, detail="Unauthorized")

    title = todo_add.get("title")
    description = todo_add.get("description")
    priority = todo_add.get("priority")

    todo_model = models.Todos(
        title=title,
        description=description,
        priority=priority,
        complete=False,
        owner_id=user.get("id")
    )

    db.add(todo_model)
    db.commit()

    db.refresh(todo_model)  # Refresh the todo model to fetch the ID generated by the database

    return todo_model


@router.put("/edit-todo/{todo_id}", response_model=schemas.Todos)
async def edit_todo_commit(request: Request, todo_id: int, title: str = Form(...),
                           description: str = Form(...), priority: int = Form(...),
                           db: Session = Depends(get_db)):

    user = await get_current_user(request)
    if user is None:
        raise HTTPException(status_code=401, detail="Unauthorized")

    todo_model = db.query(models.Todos).filter(models.Todos.id == todo_id).first()
    if todo_model is None or todo_model.owner_id != user.get("id"):
        raise HTTPException(status_code=404, detail="Todo not found")

    todo_model.title = title
    todo_model.description = description
    todo_model.priority = priority

    db.add(todo_model)
    db.commit()

    return todo_model


@router.delete("/delete/{todo_id}", status_code=204)
async def delete_todo(request: Request, todo_id: int, db: Session = Depends(get_db)):

    user = await get_current_user(request)
    if user is None:
        raise HTTPException(status_code=401, detail="Unauthorized")

    todo_model = db.query(models.Todos).filter(models.Todos.id == todo_id)\
        .filter(models.Todos.owner_id == user.get("id")).first()

    if todo_model is None:
        raise HTTPException(status_code=404, detail="Todo not found")

    db.delete(todo_model)
    db.commit()


@router.put("/complete/{todo_id}", response_model=schemas.Todos)
async def complete_todo(request: Request, todo_id: int, db: Session = Depends(get_db)):

    user = await get_current_user(request)
    if user is None:
        raise HTTPException(status_code=401, detail="Unauthorized")

    todo = db.query(models.Todos).filter(models.Todos.id == todo_id).first()

    if todo is None or todo.owner_id != user.get("id"):
        raise HTTPException(status_code=404, detail="Todo not found")

    todo.complete = not todo.complete

    db.add(todo)
    db.commit()

    return todo
